### ISSUE TITLE
Feature request: ping ips

### ISSUE THREAD

**Issue by abcdan** [lukasvdberk/ServerSightAPI#1]
Make it so serversight pingst he ips once a day to see if it can access it. This might give you some insights on the following things:

- The device is online (but just not reporting data)
- The IP is publicly accessible and not behind a firewall

**Comment by lukasvdberk** [comment]
Planned!

**Comment by abcdan** [comment]
Hyped!

**Comment by abcdan** [comment]
![image](https://user-images.githubusercontent.com/15849319/121663356-a1087500-caa6-11eb-80ac-0080854dabd8.png)

**Comment by abcdan** [comment]
![image](https://user-images.githubusercontent.com/15849319/121663514-ca290580-caa6-11eb-92ca-f81948bb1387.png)
