### ISSUE TITLE
Cluster monitoring

### ISSUE THREAD

**Issue by abcdan** [lukasvdberk/ServerSightAPI#7]
It would be awesome if I could monitor a cluster of servers, for example, that it adds up the memory or shows a graph with multiple lines for multiple servers (with different colors).

Would avoid my serversight Board filling up with billions of servers. Thanks!

**Comment by lukasvdberk** [comment]
Hi thanks for the feature request.

Unfortunately I do not think this in the scope of this project. I can add a option for webhook urls for servers so you can display it on your own application. Is that enough?

**Comment by abcdan** [comment]
![image](https://user-images.githubusercontent.com/15849319/121663078-525adb00-caa6-11eb-9134-138009f923fe.png)

**Comment by abcdan** [comment]
![image](https://user-images.githubusercontent.com/15849319/121663113-5dae0680-caa6-11eb-978b-8da18cb42387.png)

**Comment by abcdan** [comment]
![image](https://user-images.githubusercontent.com/15849319/121663156-67d00500-caa6-11eb-9653-9c460a7fa1bc.png)

**Comment by abcdan** [comment]
![image](https://user-images.githubusercontent.com/15849319/121663190-73233080-caa6-11eb-91b1-a4325f0c30b7.png)

**Comment by abcdan** [comment]
gaming?

**Comment by abcdan** [comment]
![Uploading image.png…]()

**Comment by abcdan** [comment]
![image](https://user-images.githubusercontent.com/15849319/121663261-86ce9700-caa6-11eb-8ec3-4d1fde7cb8eb.png)

**Comment by abcdan** [comment]
![image](https://user-images.githubusercontent.com/15849319/121663294-9057ff00-caa6-11eb-9d7b-cf1c1aaa0de5.png)

**Comment by abcdan** [comment]
![image](https://user-images.githubusercontent.com/15849319/121663333-99e16700-caa6-11eb-9121-54737fc61b26.png)
